[package]
name = "snake_v3"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.13"
winit = "0.28"
rand = "0.8"
rayon = "1.8"
warp = "0.3"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"