[package]
name = "snake_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pixels = "0.13"
winit = "0.27"
log = "0.4"
env_logger = "0.9"